import { MdOutlineChevronRight } from "react-icons/md";
import { FaTag, FaGift, FaClock } from "react-icons/fa";
import { IoMdClose } from "react-icons/io";
import { IoChevronDownOutline } from "react-icons/io5";
export const RightArrow = MdOutlineChevronRight;
export const Tag = FaTag;
export const Gift = FaGift;
export const Clock = FaClock;
export const Close = IoMdClose;
export const ArrowDown = IoChevronDownOutline;
