default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['RAILS_STORE_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_STORE_APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_STORE_APP_DATABASE_HOST'] %>
  port: <%= ENV['RAILS_STORE_APP_DATABASE_PORT'] %>

development:
  <<: *default
  database: rails_store_app_development

test:
  <<: *default
  database: rails_store_app_test

production:
  <<: *default
  database: rails_store_app_production
  username: <%= ENV["RAILS_STORE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_STORE_APP_DATABASE_PASSWORD"] %>
