source "https://rubygems.org"

ruby "3.3.6"

# Core Rails gems
gem "rails", "~> 7.1.3.2" 
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

# API and Authentication
gem "bcrypt", "~> 3.1.7"
gem "jwt"                     
gem "rack-cors"              
gem "active_model_serializers"

# Utility gems
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "dotenv-rails"
  gem "rspec-rails", "~> 6.1.0"  
  gem "factory_bot_rails"        
end

group :development do
  # Development tools
end